airbnb_clone2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetailView.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.DeletePhotoView.as_view(),
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete-verification"
    ),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update-profile"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
]

templates/partials/footer.html
<footer class="container mx-auto text-center py-10 border-t font-medium text-gray-500">
    <i class="fab fa-airbnb"></i> &copy; Pbnb, Inc. All rights reserved.
</footer>

templates/partials/header.html
<header>
    <h5>
        <a href="{% url "core:home" %}">GO HOME</a> | Pbnb
        <ul>
            <li><h5><a href="#">LOGIN</a></h5></li>
        </ul>
    </h5>
</header>

templates/partials/messages.html
{% if messages %}
    <ul class="absolute mx-auto left-0 right-0 flex justify-center top-0">
        {% for message in messages %}
            <li class="message
                    {% if message.tags %}{{ message.tags }}{% endif %} z-10 w-64 text-center font-medium bg-gray-700 rounded-full text-white py-3 px-6">{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

templates/partials/nav.html
<ul class="flex items-center text-sm font-medium h-full">
    {% if user.is_authenticated %}
        <li class="nav_link">
            <a href="{% url 'users:switch-hosting' %}">
                {% if request.session.is_hosting %}
                    STOP HOSTING
                {% else %}
                    START HOSTING
                {% endif %}
            </a>
        </li>
        {% if request.session.is_hosting %}
            <li class="nav_link"><a href="{% url 'rooms:create' %}">CREATE ROOM</a></li>
        {% endif %}
        <li class="nav_link"><a href="{{ user.get_absolute_url }}">PROFILE</a></li>
        <li class="nav_link"><a href="{% url "users:logout" %}">LOGOUT</a></li>
    {% else %}
        <li class="nav_link"><a href="{% url "users:login" %}">LOGIN</a></li>
        <li class="nav_link"><a href="{% url "users:signup" %}">SIGN UP</a></li>
    {% endif %}
</ul>

templates/partials/social_login.html
<div class="flex-col flex w-full">
    <a href="{% url "users:github-login" %}" class="btn border-gray-700 text-gray-700">
        <i class="fab fa-github fa-lg"></i> Continue with Github
    </a>
    <a href="{% url "users:kakao-login" %}" class="btn text-yellow-800 bg-yellow-500 border-yellow-800">
        <i class="fas fa-comment fa-lg text-yellow-800 mr-1"></i>Continue with Kakao
    </a>
</div>
<div class="flex items-center w-full my-5">
    <div class="h-px w-full bg-gray-400"></div>
    <span class="text-gray-600 font-medium mx-4 text-sm">or</span>
    <div class="h-px w-full bg-gray-400"></div>
</div>