airbnb_clone2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetailView.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.DeletePhotoView.as_view(),
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete-verification"
    ),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update-profile"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
]

rooms/models.py
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField
from core import models as core_models


# Create your models here.
class AbstractItem(core_models.TimeStampedModel):
    """ Abstract Item Definition """

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):
    """ Room Type Definition """

    class Meta:
        verbose_name = "Room Type"
        ordering = ["name"]


class Amenity(AbstractItem):
    """ Amenity Model Definition """

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):
    """ Facility Model Definition """

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):
    """ House Rule Model Definition """

    class Meta:
        verbose_name = "House Rule"


class Photo(core_models.TimeStampedModel):
    """ Photo Model Definition """

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="room_photos")
    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class Room(core_models.TimeStampedModel):
    """ Room Model Definition """

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=140)
    address = models.CharField(max_length=140, blank="True")
    price = models.IntegerField()
    guests = models.IntegerField(help_text="How many people will be staying?")
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    host = models.ForeignKey(
        "users.User", related_name="rooms", on_delete=models.CASCADE
    )
    room_type = models.ForeignKey(
        "RoomType", related_name="rooms", on_delete=models.SET_NULL, null=True
    )
    amenities = models.ManyToManyField("Amenity", related_name="rooms", blank=True)
    facilities = models.ManyToManyField("Facility", related_name="rooms", blank=True)
    house_rules = models.ManyToManyField("HouseRule", related_name="rooms", blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.city = self.city.capitalize()
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        if len(all_reviews) > 0:
            for review in all_reviews:
                all_ratings += review.rating_average()
            return round(all_ratings / len(all_reviews), 2)
        return 0

    def first_photo(self):
        try:
            (photo,) = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None

    def get_next_four_photos(self):
        photos = self.photos.all()[1:5]
        return photos

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):
    """ Search Form Definition """

    city = forms.CharField(initial="Anywhere")
    country = CountryField(default="KR").formfield()
    room_type = forms.ModelChoiceField(
        required=False, empty_label="Any Kind", queryset=models.RoomType.objects.all()
    )
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(
        required=False, help_text="How many guests do you want to be stayed?"
    )
    beds = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    super_host = forms.BooleanField(required=False)

    amenities = forms.ModelMultipleChoiceField(
        models.Amenity.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple,
        help_text="Select as many as you want.",
    )
    facilities = forms.ModelMultipleChoiceField(
        models.Facility.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple,
        help_text="Select as many as you want.",
    )


class CreatePhotoForm(forms.ModelForm):
    """ Create Photo Form """

    class Meta:
        model = models.Photo
        fields = (
            "caption",
            "file",
        )

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()


class CreateRoomForm(forms.ModelForm):
    """ Create Room Form Definition """

    class Meta:
        model = models.Room
        fields = (
            "name",
            "description",
            "country",
            "city",
            "address",
            "price",
            "guests",
            "beds",
            "bedrooms",
            "baths",
            "check_in",
            "check_out",
            "instant_book",
            "room_type",
            "amenities",
            "facilities",
            "house_rules",
        )

    def save(self, *args, **kwargs):
        room = super().save(commit=False)
        return room

rooms/views.py
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse_lazy
from django.utils import timezone
from django.shortcuts import render, redirect, reverse
from django.views.generic import (
    ListView,
    DetailView,
    View,
    UpdateView,
    FormView,
    DeleteView,
)
from django.core.paginator import Paginator
from users import mixins as user_mixins
from . import models as room_models
from . import forms as forms


class HomeView(ListView):
    """ Home View Definition """

    model = room_models.Room
    context_object_name = "room_obj_list"
    paginate_by = 12
    paginate_orphans = 5
    template_name = "rooms/room_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        now = timezone.now()
        context["now"] = now
        return context


class RoomDetailView(DetailView):
    """ Room Detail View Definition """

    # DetailView names "context_obj_name" to name of model which is "Room".
    # it turns "Room" to small letters "room" and then use it by default.
    model = room_models.Room


class SearchView(View):
    """ Search View Definition """

    def get(self, request):

        country = request.GET.get("country")

        if country:
            form = forms.SearchForm(request.GET)

            if form.is_valid():
                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                beds = form.cleaned_data.get("beds")
                bedrooms = form.cleaned_data.get("bedrooms")
                baths = form.cleaned_data.get("baths")
                instant_book = form.cleaned_data.get("instant_book")
                super_host = form.cleaned_data.get("super_host")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")

                filter_args = {}

                if city != "Anywhere":
                    filter_args["city__startswith"] = city

                filter_args["country"] = country

                if room_type is not None:
                    filter_args["room_type__pk"] = room_type

                if price is not None:
                    filter_args["price__lte"] = price

                if guests is not None:
                    filter_args["guests__gte"] = guests

                if beds is not None:
                    filter_args["beds__lte"] = beds

                if bedrooms is not None:
                    filter_args["bedrooms__lte"] = bedrooms

                if baths is not None:
                    filter_args["baths__lte"] = baths

                if instant_book:
                    filter_args["instant_book"] = True

                if super_host:
                    filter_args["host__super_host"] = True

                for amenity in amenities:
                    filter_args["amenities"] = amenity

                for facility in facilities:
                    filter_args["facilities"] = facility

                qs = room_models.Room.objects.filter(**filter_args).order_by("-created")
                paginator = Paginator(qs, 10, orphans=5)
                page = request.GET.get("page", 1)
                rooms = paginator.get_page(page)

                return render(
                    request, "rooms/search.html", {"form": form, "rooms": rooms},
                )
        else:
            form = forms.SearchForm()

        return render(request, "rooms/search.html", {"form": form},)


"""
def room_detail(request, pk):
    try:
        room = room_models.Room.objects.get(pk=pk)
        return render(request, "rooms/room_detail.html", {"room": room})
    except room_models.Room.DoesNotExist:
        raise Http404()
        # return redirect(reverse("core:home"))

def all_rooms(request):
    all_my_rooms = room_models.Room.objects.all()

    page_num = request.GET.get("page")
    paginator = Paginator(all_my_rooms, 10, orphans=5)
    room = paginator.get_page(page_num)

    return render(request, "rooms/room_list.html", context={"all_my_rooms": room,},)
"""


class EditRoomView(user_mixins.LoggedInOnlyView, UpdateView):
    """ Edit Room View Definition """

    model = room_models.Room
    template_name = "rooms/room_edit.html"

    fields = (
        "name",
        "description",
        "country",
        "city",
        "address",
        "price",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    )

    def get_object(self, queryset=None):
        room = super(EditRoomView, self).get_object()
        if room.host.pk != self.request.user.pk:
            raise Http404()
        else:
            return room


class RoomPhotosView(user_mixins.LoggedInOnlyView, DetailView):
    """ Room Photos View Definition """

    model = room_models.Room
    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):
        room = super(RoomPhotosView, self).get_object()
        if room.host.pk != self.request.user.pk:
            raise Http404()
        else:
            return room


@login_required
def delete_photo(request, room_pk, photo_pk):
    user = request.user
    try:
        room = room_models.Room.objects.get(pk=room_pk)
        if room.host.pk != user.pk:
            messages.error(request, "You are not allowed to delete this photo.")
        else:
            room_models.Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, "사진이 삭제되었습니다")
        return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))
    except room_models.Room.DoesNotExist:
        return redirect(reverse("core:home"))


class DeletePhotoView(user_mixins.LoggedInOnlyView, DeleteView):
    """ Delete Photo View Definition """

    model = room_models.Photo
    pk_url_kwarg = "photo_pk"

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        messages.success(self.request, "사진이 삭제되었습니다")
        return reverse("rooms:photos", kwargs={"pk": room_pk})


class EditPhotoView(user_mixins.LoggedInOnlyView, UpdateView):
    """ Edit Photo View """

    model = room_models.Photo
    template_name = "rooms/photo_edit.html"
    pk_url_kwarg = "photo_pk"
    fields = ("caption",)

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        messages.success(self.request, "사진설명이 변경되었습니다")
        return reverse("rooms:photos", kwargs={"pk": room_pk})


class AddPhotoView(user_mixins.LoggedInOnlyView, FormView):
    """ Add Photo View Definition """

    template_name = "rooms/photo_create.html"
    form_class = forms.CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)
        messages.success(self.request, "Photo has been added successfully")
        return redirect(reverse("rooms:photos", kwargs={"pk": pk}))

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["room_pk"] = self.kwargs.get("pk")
        return context


class CreateRoomView(user_mixins.LoggedInOnlyView, FormView):
    """ Create Room View Definition """

    form_class = forms.CreateRoomForm
    template_name = "rooms/room_create.html"

    def form_valid(self, form):
        room = form.save()
        room.host = self.request.user
        room.save()
        form.save_m2m()
        messages.success(request=self.request, message="Room has been created")
        return redirect(reverse("rooms:detail", kwargs={"pk": room.pk}))

templates/rooms/photo_confirm_delete.html
{% extends "base.html" %}
{% block page_title %}DELETE PHOTO CONFIRMATION{% endblock page_title %}
{% block search-bar %}{% comment %}  Hide search-bar  {% endcomment %}{% endblock search-bar %}

{% block content %}
    <div class="container w-4/12 lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-16 flex flex-col items-center border p-6 border-gray-400">

        <form method="post">{% csrf_token %}
            <p class="font-semibold text-lg mt-6 mb-16">정말로 삭제하시겠습니까?</p>
            <input type="submit" value="CLICK TO CONFIRM"
                   class="text-white font-semibold text-center bg-red-400 hover:bg-indigo-400 cursor-pointer">
        </form>

        <div class="mt-3 container flex w-full justify-center">
            <a href="{% url 'rooms:photos' object.room.pk %}"
               class="text-indigo-500 font-semibold hover:underline">아니오</a>
        </div>
    </div>
{% endblock content %}

templates/rooms/photo_create.html
{% extends "base.html" %}
{% block page_title %}ADD PHOTOS{% endblock page_title %}
{% block search-bar %}{% comment %}  Hide search-bar  {% endcomment %}{% endblock search-bar %}

{% block content %}
    <div class="container w-4/12 lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-16 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/room/room_form.html' with form=form cta="사 진 추 가" %}

        <div class="mt-3 container flex w-full justify-center">
            <a href="{% url "rooms:photos" room_pk %}" class="text-indigo-500 font-semibold hover:underline">돌아가기</a>
        </div>
    </div>
{% endblock content %}

templates/rooms/photo_edit.html
{% extends "base.html" %}
{% block page_title %}UPDATE PHOTO{% endblock page_title %}
{% block search-bar %}{% comment %}  Hide search-bar  {% endcomment %}{% endblock search-bar %}

{% block content %}
    <div class="lg:w-5/12 md:w-1/2 xl:w-1/4 container mx-auto p-6 my-10 flex flex-col items-center border border-gray-400">

        {% include 'mixins/room/room_form.html' with form=form cta="CLICK TO UPDATE" %}

        <div class="mt-3 container flex w-full justify-center">
            <a href="{% url 'rooms:photos' object.room.pk %}"
               class="text-indigo-500 font-semibold hover:underline">돌아가기</a>
        </div>
    </div>
{% endblock content %}

templates/rooms/room_create.html
{% extends "base.html" %}
{% block page_title %}CREATE ROOM{% endblock page_title %}
{% block search-bar %}{% comment %}  Hide search-bar  {% endcomment %}{% endblock search-bar %}

{% block content %}
    <div class="lg:w-5/12 md:w-1/2 xl:w-1/4 container mx-auto p-6 my-10 flex flex-col items-center border border-gray-400">

        {% include 'mixins/room/room_form.html' with form=form cta="CLICK TO UPDATE" %}

        <div class="mt-3 container flex w-full justify-between">
            <a href="{% url "core:home" %}" class="text-black font-semibold hover:underline">CANCEL</a>
        </div>
    </div>
{% endblock content %}

templates/rooms/room_detail.html
{% extends "base.html" %}
{% block page_title %}{{ room.name }}'s DETAIL{% endblock %}
{% block content %}

    <div class="container max-w-full h-75vh mb-20 flex -mt-5 border border-gray-500">
        <div class="h-full w-1/2 bg-cover bg-center border border-gray-500 hover:bg-auto"
             style="background-image: url('{{ room.first_photo }}')"></div>
        <div class="h-full w-1/2 flex flex-wrap">
            {% for next_photo in room.get_next_four_photos %}
                <div class="bg-cover w-1/2 h-auto bg-center border border-gray-500 hover:bg-auto"
                     style="background-image: url('{{ next_photo.file.url }}')"></div>
            {% endfor %}
        </div>
    </div>

    <div class="container mx-auto flex justify-around pb-56">
        <div class="w-1/2">
            <div class="container flex justify-between">
                <div class="mb-5">
                    <h4><span class="text-3xl font-medium mb-px">{{ room.name }}</span></h4>
                    <span class="font-light mb-px text-gray-500">{{ room.city }}</span>
                </div>
                <a href="{{ room.host.get_absolute_url }}" class="flex flex-col items-center">
                    {% include 'mixins/user_avatar.html' with user=room.host %}
                    <span class="font-light mt-2 text-gray-500 truncate block">{{ room.host.first_name }} {{ room.host.last_name }}</span>
                </a>
            </div>
            <div class="container flex border-section">
                <span class="mr-5 font-light">{{ room.room_type }}</span>
                <span class="mr-5 font-light">{{ room.beds }} bed{{ room.beds|pluralize }}</span>
                <span class="mr-5 font-light">{{ room.bedrooms }} bedroom{{ room.bedrooms|pluralize }}</span>
                <span class="mr-5 font-light">{{ room.baths }} bath{{ room.baths|pluralize }}</span>
                <span class="mr-5 font-light">{{ room.guests }} guest{{ room.guests|pluralize }}</span>

            </div>
            <p class="border-section">
                {{ room.description }}
            </p>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">Amenities</h4>
                {% for ame in room.amenities.all %}
                    <li class="mb-2">{{ ame }}</li>
                {% endfor %}
            </div>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">Facilities</h4>
                {% for ame in room.facilities.all %}
                    <li class="mb-2">{{ ame }}</li>
                {% endfor %}
            </div>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">House Rules</h4>
                {% for ame in room.house_rules.all %}
                    <li class="mb-2">{{ ame }}</li>
                {% endfor %}
            </div>
            <div class="mt-10">
                <h4 class="font-medium text-2xl mb-5">Reviews</h4>
                <div class="flex items-center">
                    <div>
                        <i class="fas fa-star text-teal-500"></i>
                        <span class="font-bold text-xl">{{ room.total_rating }}</span>
                    </div>
                    <div class="h-4 w-px bg-gray-400 mx-5"></div>
                    <div>
                        <span class="font-bold text-xl">{{ room.reviews.count }}</span>
                        <span>review{{ room.reviews.count|pluralize }}</span>
                    </div>
                </div>
                <div class="mt-10">
                    {% for review in room.reviews.all %}
                        <a href="{% url 'users:profile' review.user.pk %}">
                            <div class="border-section">
                                <div class="mb-3 flex">
                                    <div>
                                        {% include "mixins/user_avatar.html" with user=review.user h_and_w='w-10 h-10' text='text-xl' %}
                                    </div>
                                    <div class="flex flex-col ml-5">
                                        <span class="font-medium">{{ review.user.first_name }}</span>
                                        <span class="text-sm text-gray-500">{{ review.created|date:'F Y' }}</span>
                                    </div>
                                </div>
                        </a>
                        <p>{{ review.review }}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="w-1/3">
            {% if room.host == user %}
                <a href="{% url "rooms:edit" room.pk %}" class="btn-link block hover:bg-indigo-400">EDIT ROOM</a>
            {% endif %}
        </div>
    </div>

{% endblock %}

templates/rooms/room_edit.html
{% extends "base.html" %}
{% block page_title %}UPDATE ROOM{% endblock page_title %}
{% block search-bar %}{% comment %}  Hide search-bar  {% endcomment %}{% endblock search-bar %}

{% block content %}
    <div class="lg:w-5/12 md:w-1/2 xl:w-1/4 container mx-auto p-6 my-10 flex flex-col items-center border border-gray-400">

        {% include 'mixins/room/room_form.html' with form=form cta="CLICK TO UPDATE" %}

        <div class="mt-3 container flex w-full justify-between">
            <a href="{% url "rooms:detail" room.pk %}" class="text-black font-semibold hover:underline">CANCEL</a>
            {% if object.login_method == "email" %}
                <a href="{% url "users:password" %}" class="text-teal-500 font-semibold hover:underline">CHANGE
                    PASSWORD</a>
            {% endif %}
        </div>
    </div>
{% endblock content %}

templates/rooms/room_photos.html
{% extends "base.html" %}
{% block page_title %}UPDATE PHOTOS{% endblock page_title %}
{% block search-bar %}{% comment %}  Hide search-bar  {% endcomment %}{% endblock search-bar %}

{% block content %}
    <div class="container mx-auto my-10 flex flex-col">
        <a href="{% url 'rooms:add-photo' room.pk %}" class="btn-link mt-10 hover:bg-indigo-400">사 진 추 가 하 기</a>
        <div class="mt-10">현재 {{ room.photos.count }}개의 사진이 있습니다.</div>
        {% for photo in room.photos.all %}
            <div class="mb-5 border p-6 border-gray-400 flex justify-between">
                <div class="flex items-start">
                    <img src="{{ photo.file.url }}" class="w-32 h-32"/>
                    <span class="ml-5 text-xl">{{ photo.caption }}</span>
                </div>
                <div class="flex flex-col w-1/5">
                    <a class="btn-link mb-5 bg-teal-500" href="{% url 'rooms:edit-photo' room.pk photo.pk %}">Edit</a>
                    <a class="btn-link bg-red-600" href="{% url 'rooms:delete-photo' room.pk photo.pk %}">Delete</a>
                </div>
            </div>
        {% endfor %}
        <div class="mt-3 container flex w-full justify-center">
            <a href="{% url "rooms:edit" room.pk %}" class="text-indigo-500 font-semibold hover:underline">돌아가기</a>
        </div>
    </div>
{% endblock content %}

templates/rooms/search.html
{% extends "base.html" %}
{% block page_title %}
    SEARCH
{% endblock %}
{% block content %}
    <h1>SEARCH</h1>
    <h4>Searching by {{ city }}</h4>
    {% block search-bar %}
        {% comment %}  Hide search-bar  {% endcomment %}
    {% endblock %}
    <form method="get" action="{% url "rooms:search" %}">
        {{ form.as_p }}
        <button>SEARCH</button>
        <br>
    </form>

    <h3>RESULTs</h3>
    {% for room in rooms %}
        <h3>{{ room.name }}</h3>
    {% endfor %}

{% endblock %}

templates/rooms/search_nogada.html
{% extends "base.html" %}
{% block page_title %}
    SEARCH
{% endblock %}
{% block content %}
    <h1>SEARCH</h1>
    <h4>Searching by {{ city }}</h4>
    {% block search-bar %}
        {% comment %}  Hide search-bar  {% endcomment %}
    {% endblock %}
    <form method="get" action="{% url "rooms:search" %}">
        <div><label for="city">City</label>
            <input value="{{ city }}" id="city" name="city" placeholder="Search by city">
        </div>
        <br>
        <div>
            <label for="country">Country</label>
            <select id="country" name="country">
                {% for country in countries %}
                    <option value="{{ country.code }}"
                            {% if country.code == s_country %}selected{% endif %}>{{ country.name }}</option>
                {% endfor %}
            </select>
        </div>
        <br>
        <div>
            <label for="room_type">Room Types</label>
            <select id="room_type" name="room_type">
                <option value="0" {% if s_room_type == 0 %}selected{% endif %}>Any Kind</option>
                {% for room_type in room_types %}
                    <option value="{{ room_type.pk }}"
                            {% if room_type.pk == s_room_type %}selected{% endif %}>{{ room_type.name }}</option>
                {% endfor %}
            </select>
        </div>
        <br>
        <div><label for="price">Price</label>
            <input value="{{ s_price }}" type="number" id="price" name="price" placeholder="Price">
        </div>
        <br>
        <div><label for="guests">Guests</label>
            <input value="{{ s_guest }}" type="number" id="guests" name="guests" placeholder="Guests">
        </div>
        <br>
        <div><label for="beds">Beds</label>
            <input value="{{ s_bed }}" type="number" id="beds" name="beds" placeholder="Beds">
        </div>
        <br>
        <div><label for="bedrooms">Bedrooms</label>
            <input value="{{ s_bedroom }}" type="number" id="bedrooms" name="bedrooms" placeholder="Bedrooms">
        </div>
        <br>
        <div><label for="baths">Baths</label>
            <input value="{{ s_bath }}" type="number" id="baths" name="baths" placeholder="Baths">
        </div>
        <br>
        <div><label for="instant">Instant Book Only?</label>
            <input type="checkbox" id="instant" name="instant"
                   {% if instant %}checked{% endif %}/>
        </div>
        <br>
        <div><label for="super_host">Is Super Host?</label>
            <input type="checkbox" id="super_host" name="super_host"
                   {% if super_host %}checked{% endif %}/>
        </div>
        <br>
        <div>
            <h3>Amenities</h3>
            <ul>
                {% for amenity in amenities %}
                    <li>
                        <label for="a_{{ amenity.pk }}">{{ amenity.name }}</label>
                        <input value="{{ amenity.pk }}" type="checkbox" id="a_{{ amenity.pk }}"
                               name="amenities" placeholder="Amenities"
                                {% if amenity.pk|slugify in s_amenities %}
                               checked{% endif %}
                        >
                    </li>
                {% endfor %}
            </ul>
        </div>
        <br>
        <div>
            <h3>Facilities</h3>
            <ul>
                {% for facility in facilities %}
                    <li>
                        <label for="f_{{ facility.pk }}">{{ facility.name }}</label>
                        <input value="{{ facility.pk }}" type="checkbox" id="f_{{ facility.pk }}"
                               name="facilities" placeholder="Facilities"
                                {% if facility.pk|slugify in s_facilities %}
                               checked{% endif %}
                        >
                    </li>
                {% endfor %}
            </ul>
        </div>
        <br>
        <button>SEARCH</button>
        <br>
    </form>

    <h3>RESULTs</h3>
    {% for room in rooms %}
        <h3>{{ room.name }}</h3>
    {% endfor %}

{% endblock %}