airbnb_clone2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete-verification"
    ),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update-profile"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
]

users/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django.utils.html import strip_tags
from django.template.loader import render_to_string


class User(AbstractUser):
    """ Custom User Model Definition """

    GENDER_MALE = "male"
    GENDER_FEMALE = "female"
    GENDER_OTHER = "other"

    GENDER_CHOICES = (
        (GENDER_MALE, "Male"),
        (GENDER_FEMALE, "Female"),
        (GENDER_OTHER, "Other"),
    )

    LANGUAGE_ENGLISH = "en"
    LANGUAGE_KOREAN = "kr"

    LANGUAGE_CHOICES = ((LANGUAGE_ENGLISH, "English"), (LANGUAGE_KOREAN, "Korean"))

    CURRENCY_USD = "usd"
    CURRENCY_KRW = "krw"

    CURRENCY_CHOICES = ((CURRENCY_USD, "USD"), (CURRENCY_KRW, "KRW"))

    LOGIN_EMAIL = "email"
    LOGIN_GITHUB = "github"
    LOGIN_KAKAO = "kakao"

    LOGIN_CHOICES = (
        (LOGIN_EMAIL, "Email"),
        (LOGIN_GITHUB, "Github"),
        (LOGIN_KAKAO, "Kakao"),
    )

    avatar = models.ImageField(upload_to="avatars", blank=True)
    gender = models.CharField(choices=GENDER_CHOICES, max_length=10, blank=True)
    bio = models.TextField(blank=True)
    birth_date = models.DateField(blank=True, null=True)
    language = models.CharField(
        choices=LANGUAGE_CHOICES, blank=True, max_length=2, default=LANGUAGE_KOREAN
    )
    currency = models.CharField(
        choices=CURRENCY_CHOICES, blank=True, max_length=3, default=CURRENCY_KRW
    )
    super_host = models.BooleanField(default=False)
    email_confirmed = models.BooleanField(default=False)
    email_secret = models.CharField(max_length=20, default="")
    login_method = models.CharField(
        choices=LOGIN_CHOICES, max_length=8, default=LOGIN_EMAIL
    )

    def get_absolute_url(self):
        """
        어드민 패널에서 View on site 버튼을 활성화하기 위해 오버라이드 한다
        또한, 템플릿에서 users:profile 대신 {{user.get_absolute_url}} 사용가능해짐
        """
        return reverse("users:profile", kwargs={"pk": self.pk})

    def verify_email(self):
        """ Send verification email to user's email """
        if self.email_confirmed is False:
            secret = uuid.uuid4().hex[:20]
            self.email_secret = secret
            html_message = render_to_string(
                "emails/verify_email.html", {"secret": secret}
            )
            send_mail(
                "Verify email for Pbnb from My Office",
                strip_tags(html_message),
                settings.EMAIL_FROM,
                [self.email],
                html_message=html_message,
            )
            self.save()

        return

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from . import models


class LoginForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={"placeholder": "Email Address"})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("Password is wrong"))
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError("User does not exist"))


class SignUpForm(UserCreationForm):
    class Meta:
        model = models.User
        fields = (
            "first_name",
            "last_name",
            "username",
        )
        widgets = {
            "first_name": forms.TextInput(attrs={"placeholder": "First Name"}),
            "last_name": forms.TextInput(attrs={"placeholder": "Last Name"}),
            "username": forms.EmailInput(attrs={"placeholder": "Email Address"}),
        }

    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password"})
    )


class UpdateProfileForm(forms.ModelForm):
    """ Update Profile Form Definition """

    avatar = forms.ImageField(
        required=False, widget=forms.FileInput, label="Upload Profile Image"
    )

    class Meta:
        model = models.User
        fields = [
            "first_name",
            "last_name",
            "avatar",
            "gender",
            "bio",
            "birth_date",
            "language",
            "currency",
        ]
        widgets = {
            "first_name": forms.TextInput(attrs={"placeholder": "First Name"}),
            "last_name": forms.TextInput(attrs={"placeholder": "Last Name"}),
            "bio": forms.Textarea(attrs={"placeholder": "Biography"}),
            "birth_date": forms.DateInput(attrs={"placeholder": "yyyy-mm-dd"}),
        }

users/views.py
import os
import requests
from django.views.generic import FormView, DetailView, UpdateView
from django.urls import reverse_lazy
from django.shortcuts import redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.core.files.base import ContentFile
from django.contrib import messages
from . import forms, models, mixins


class LoginView(mixins.LoggedOutOnlyView, FormView):
    template_name = "users/login.html"
    form_class = forms.LoginForm

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            messages.success(self.request, f"Welcome back {user.first_name}")
            login(self.request, user)
        return super().form_valid(form)

    def get_success_url(self):
        get_next_url = self.request.GET.get("next")
        if get_next_url is not None:
            return get_next_url
        else:
            return reverse("core:home")


def log_out(request):
    messages.info(request, f"Good Bye! {request.user.first_name}")
    logout(request)
    return redirect(reverse("users:login"))


class SignUpView(mixins.LoggedOutOnlyView, FormView):
    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password2")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            messages.success(self.request, f"Welcome {user.first_name}")
            login(self.request, user)
        if user.email == "":
            user.email = email
        user.verify_email()
        return super().form_valid(form)


def complete_verification(request, key):
    try:
        user = models.User.objects.get(email_secret=key)
        user.email_confirmed = True
        user.email_secret = ""
        user.save()
        # todo add success message
    except models.User.DoesNotExist:
        # todo add error message
        pass
    return redirect(reverse("core:home"))


class GithubException(Exception):
    pass


def github_login(request):
    client_id = os.environ.get("GH_USERNAME")
    redirect_uri = "http://127.0.0.1:8000/users/login/github/callback"
    return redirect(
        f"https://github.com/login/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&scope=read:user"
    )


def github_callback(request):
    try:
        code = request.GET.get("code", None)
        client_id = os.environ.get("GH_USERNAME")
        client_secret = os.environ.get("GH_SECRET")
        if code is not None:
            result = requests.post(
                f"https://github.com/login/oauth/access_token?client_id={client_id}&client_secret={client_secret}&code={code}",
                headers={"Accept": "application/json"},
            )
            result_json = result.json()
            error = result_json.get("error", None)
            if error is not None:
                return redirect(reverse("users:login"))
            else:
                access_token = result_json.get("access_token")
                profile_request = requests.get(
                    "https://api.github.com/user",
                    headers={
                        "Authorization": f"token {access_token}",
                        "Accept": "application/json",
                    },
                )
                profile_json = profile_request.json()
                username = profile_json.get("login", None)
                if username is not None:
                    name = username
                    email = profile_json.get("email")
                    bio = profile_json.get("bio")
                    try:
                        user = models.User.objects.get(email=email)
                        if user.login_method != models.User.LOGIN_GITHUB:
                            raise GithubException(
                                f"Please log in with: {user.login_method}"
                            )
                    except models.User.DoesNotExist:
                        user = models.User.objects.create(
                            username=email,
                            email=email,
                            first_name=name,
                            bio=bio,
                            login_method=models.User.LOGIN_GITHUB,
                        )
                        user.set_unusable_password()
                        user.save()
                    messages.success(request, f"Welcome back {user.first_name}")
                    login(request, user)
                    return redirect(reverse("core:home"))
                else:
                    raise GithubException("Can't get your profile")
        else:
            raise GithubException("Can't get the authorization code")
    except GithubException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


def kakao_login(request):
    client_id = os.environ.get("KAKAO_ID")
    redirect_uri = "http://127.0.0.1:8000/users/login/kakao/callback"

    return redirect(
        f"https://kauth.kakao.com/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&response_type=code"
    )


class KakaoException(Exception):
    pass


def kakao_callback(request):
    try:
        client_id = os.environ.get("KAKAO_ID")
        client_secret = os.environ.get("KAKAO_KEY")
        redirect_uri = "http://127.0.0.1:8000/users/login/kakao/callback"
        code = request.GET.get("code", None)
        if code is not None:
            token_request = requests.post(
                f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={client_id}&client_secret={client_secret}&code={code}&redirect_uri={redirect_uri}",
            )
            token_json = token_request.json()
            error = token_json.get("error", None)
            if error is not None:
                raise KakaoException("Can't get the access token")
            else:
                access_token = token_json.get("access_token")
                profile_request = requests.get(
                    "https://kapi.kakao.com/v2/user/me",
                    headers={"Authorization": f"Bearer {access_token}",},
                )
                profile_json = profile_request.json()
                kakao_account = profile_json.get("kakao_account")
                properties = profile_json.get("properties")
                profile = kakao_account.get("profile")
                email = kakao_account.get("email", None)
                if email is not None:
                    name = profile.get("nickname")
                    gender = kakao_account.get("gender")
                    profile_image = properties.get("profile_image")
                    try:
                        user = models.User.objects.get(email=email)
                        if user.login_method != models.User.LOGIN_KAKAO:
                            raise KakaoException(
                                f"Please log in with: {user.login_method}"
                            )
                    except models.User.DoesNotExist:
                        user = models.User.objects.create(
                            username=email,
                            first_name=name,
                            email=email,
                            gender=gender,
                            login_method=models.User.LOGIN_KAKAO,
                            email_confirmed=True,
                        )
                        user.set_unusable_password()
                        user.save()
                        if profile_image is not None:
                            photo_request = requests.get(profile_image)
                            user.avatar.save(
                                f"{email}-avatar", ContentFile(photo_request.content)
                            )
                    messages.success(request, f"Welcome back {user.first_name}")
                    login(request, user)
                    return redirect(reverse("core:home"))
                else:
                    raise KakaoException("Can't get your profile")
        else:
            raise KakaoException("Can't get the authorization code")
    except KakaoException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


class UserProfileView(DetailView):
    """
    User Profile View Definition
    Nomadcoder Lesson #21.3 참조
    페이지 이동에 따라 유저가 변경되는 구조에 따라
    context_obj_name 을 설정하여 어느 페이지에서든
    오른쪽 상단의 PROFILE 버튼을 클릭 시
    '로그인한 유저'에 대한 프로파일 페이지로 이동하게 한다.
    """

    model = models.User
    context_object_name = "user_obj"

    def get_context_data(self, *, object_list=None, **kwargs):
        """
        super().get_context_data(**kwargs) 이 구문은 위 context_object_name 을
        불러온다(기본값). 추가 인자를 불러오고 싶을 때, get_context_data 를
        오버라이드 하여 추가할 수 있다. 아래의 Hello 문 처럼 배열에 추가한다.
        """
        context = super().get_context_data(**kwargs)
        context["hello"] = "Hello!"
        # html 파일에서 {{hello}} 로 불러 사용한다.
        return context


class UpdateProfileView(mixins.LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """
    Update Profile View Definition :
    UpdateView 클래스뷰 사용 시, urls.py 에 path 입력 시, <int:pk> 와 같은
    형식으로 url 을 부여하면 자동으로 모든 update 프로세스를 만들어 준다.
    그러나, 지금처럼 update-profile 형식의 path 설정 시, get_object() 를
    오버라이드 하여, 내가 원하는 스타일로 커스터마이징 할 수 있다.
    """

    model = models.User
    form_class = forms.UpdateProfileForm
    template_name = "users/update-profile.html"

templates/users/login.html
{% extends "base.html" %}
{% block page_title %}USER LOGIN{% endblock page_title %}
{% block search-bar %}{% comment %}  Hide search-bar  {% endcomment %}{% endblock search-bar %}

{% block content %}
    <div class="lg:w-5/12 md:w-1/2 xl:w-1/4 container mx-auto p-6 my-10 flex flex-col items-center border border-gray-400">
        {% include "partials/social_login.html" %}
        {% include "mixins/auth/auth_form.html" with form=form cta="LOGIN" %}

        <div class="mt-3">
            <span class="mr-2">Don't have an account. <a href="{% url "users:signup" %}"
                                                         class="text-teal-500 font-semibold">SIGN UP</a></span>
        </div>
    </div>
{% endblock content %}

templates/users/signup.html
{% extends "base.html" %}
{% block page_title %}SIGN UP{% endblock page_title %}
{% block search-bar %}{% comment %}  Hide search-bar  {% endcomment %}{% endblock search-bar %}

{% block content %}
    <div class="lg:w-5/12 md:w-1/2 xl:w-1/4 container mx-auto p-6 my-10 flex flex-col items-center border border-gray-400">
        {% include "partials/social_login.html" %}
        {% include 'mixins/auth/auth_form.html' with form=form cta="SIGN UP" %}

        <div class="mt-3">
            <span class="mr-2">You have an account. <a href="{% url "users:login" %}"
                                                       class="text-teal-500 font-semibold">LOGIN</a></span>
        </div>
    </div>
{% endblock content %}

templates/users/update-password.html
{% extends "base.html" %}
{% block page_title %}UPDATE PASSWORD{% endblock page_title %}
{% block search-bar %}{% comment %}  Hide search-bar  {% endcomment %}{% endblock search-bar %}

{% block content %}
    <div class="h-75vh">
        <div class="lg:w-5/12 md:w-1/2 xl:w-1/4 container mx-auto p-6 my-10 flex flex-col items-center border border-gray-400">

            {% include 'mixins/auth/auth_form.html' with form=form cta="CLICK TO UPDATE" %}

            <div class="mt-3 container flex w-full justify-between">
                <a href="{% url "users:update-profile" %}" class="text-black font-semibold hover:underline">CANCEL</a>
            </div>
        </div>
    </div>
{% endblock content %}

templates/users/update-profile.html
{% extends "base.html" %}
{% block page_title %}UPDATE PROFILE{% endblock page_title %}
{% block search-bar %}{% comment %}  Hide search-bar  {% endcomment %}{% endblock search-bar %}

{% block content %}
    <div class="lg:w-5/12 md:w-1/2 xl:w-1/4 container mx-auto p-6 my-10 flex flex-col items-center border border-gray-400">

        {% include 'mixins/auth/auth_form.html' with form=form cta="CLICK TO UPDATE" %}

        <div class="mt-3 container flex w-full justify-between">
            <a href="{% url "users:profile" user.pk %}" class="text-black font-semibold hover:underline">CANCEL</a>
            {% if object.login_method == "email" %}
                <a href="{% url "users:password" %}" class="text-teal-500 font-semibold hover:underline">CHANGE
                    PASSWORD</a>
            {% endif %}
        </div>
    </div>
{% endblock content %}

templates/users/user_detail.html
{% extends "base.html" %}
{% block page_title %}{{ user_obj.first_name.capitalize }}'s PROFILE{% endblock page_title %}

{% block content %}
    <div class="min-h-75vh">
        <div class="lg:w-5/12 md:w-1/2 xl:w-1/4 container mx-auto p-6 my-10 flex flex-col items-center border border-gray-400">

            {% include "mixins/user_avatar.html" with user=user_obj %}
            <div class="flex items-center">
                <span class="text-3xl mt-1">{{ user_obj.first_name }} {{ user_obj.last_name }}</span>
                {% if user_obj.super_host %}
                    <i class="fas fa-check-circle text-teal-400 ml-2" title="SUPER HOST"></i> {% endif %}
            </div>
            <span class="mt-1 mb-6 text-xl">{{ user_obj.bio }}</span>
            {% if user == user_obj %}
                <a href="{% url "users:update-profile" %}" class="btn-link">EDIT PROFILE</a>
            {% endif %}

        </div>
        {% if user_obj.rooms.count > 0 %}
            <h3 class="mb-12 text-2xl text-center">{{ user_obj.first_name.capitalize }}'s Rooms</h3>
            <div class="container mx-auto pb-10 ">
                <div class="flex flex-wrap -mx-40 mb-10">
                    {% for room in user_obj.rooms.all %}
                        {% include 'mixins/room_card.html' with room=room %}
                    {% endfor %}
                </div>
            </div>
        {% endif %}
    </div>
{% endblock content %}